// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularEfCore.Context;

namespace ModularEfCore.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180919185443_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModularEfCore.Example.Database.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("FirstName")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName");

                    b.HasKey("Id")
                        .HasName("PK_Customer");

                    b.ToTable("Sample","Customer");

                    b.HasData(
                        new { Id = 1, FirstName = "Philipp", LastName = "Wagner" },
                        new { Id = 2, FirstName = "Max", LastName = "Mustermann" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
